import builtins from "builtin-modules";
import esbuild from "esbuild";

const production = process.argv[2] === "production";

const banner =
  "/*\n" +
  "THIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n" +
  "If you want to view the source, please visit the Github repository of this plugin.\n" +
  "*/";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production,
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.rebuild();
  await context.dispose();
}
